# Generated by Django 5.2.8 on 2025-11-13 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da especialidade médica (ex: Cardiologia, Pediatria)', max_length=100, unique=True, verbose_name='Nome da Especialidade')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da especialidade', verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a especialidade está ativa no sistema', verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do profissional de saúde', max_length=200, verbose_name='Nome Completo')),
                ('crm', models.CharField(help_text='Número do CRM (Conselho Regional de Medicina)', max_length=8, validators=[django.core.validators.RegexValidator(message='CRM deve conter entre 4 e 8 dígitos numéricos', regex='^\\d{4,8}$')], verbose_name='CRM')),
                ('uf_crm', models.CharField(default='MT', help_text='Estado do CRM (ex: MT, SP, RJ)', max_length=2, verbose_name='UF do CRM')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato', max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o profissional está ativo no sistema', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('especialidade', models.ForeignKey(help_text='Especialidade médica do profissional', on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='app_medpass.especialidade', verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['nome'],
                'unique_together': {('crm', 'uf_crm')},
            },
        ),
    ]
