# Generated by Django 5.2.8 on 2025-11-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_medpass", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Senha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Número da senha gerada (ex: N001, P002, U003)",
                        max_length=10,
                        verbose_name="Número da Senha",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("N", "Normal"),
                            ("P", "Preferencial"),
                            ("U", "Urgência"),
                        ],
                        default="N",
                        help_text="Tipo da senha (Normal, Preferencial, Urgência)",
                        max_length=1,
                        verbose_name="Tipo de Senha",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando"),
                            ("chamando", "Chamando"),
                            ("atendendo", "Em Atendimento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="aguardando",
                        help_text="Status atual da senha",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "guiche",
                    models.CharField(
                        blank=True,
                        help_text="Número do guichê de atendimento",
                        max_length=10,
                        verbose_name="Guichê",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "chamado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Chamada"
                    ),
                ),
                (
                    "atendido_em",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Início do Atendimento",
                    ),
                ),
                (
                    "concluido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "especialidade",
                    models.ForeignKey(
                        help_text="Especialidade para qual a senha foi gerada",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="senhas",
                        to="app_medpass.especialidade",
                        verbose_name="Especialidade",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profissional que está atendendo a senha",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="senhas_atendidas",
                        to="app_medpass.profissional",
                        verbose_name="Profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Senha",
                "verbose_name_plural": "Senhas",
                "ordering": ["-criado_em"],
            },
        ),
    ]
